function(_detect_wsl)
    set(osrelease_path /proc/sys/kernel/osrelease)
    if (NOT EXISTS "${osrelease_path}")
        set(WSL OFF PARENT_SCOPE)
        return()
    endif()

    file(READ "${osrelease_path}" osrelease)
    string(TOLOWER "${osrelease}" osrelease)
    if (osrelease MATCHES "^.*(microsoft|wsl).*$")
        set(WSL ON PARENT_SCOPE)
    else()
        set(WSL OFF PARENT_SCOPE)
    endif()
endfunction()

_detect_wsl()
message(STATUS "Executing inside WSL: ${WSL}")
